// Generated by gencpp from file opt_msgs/KeyPoint.msg
// DO NOT EDIT!


#ifndef OPT_MSGS_MESSAGE_KEYPOINT_H
#define OPT_MSGS_MESSAGE_KEYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opt_msgs
{
template <class ContainerAllocator>
struct KeyPoint_
{
  typedef KeyPoint_<ContainerAllocator> Type;

  KeyPoint_()
    : x_pos(0.0)
    , y_pos(0.0)
    , angle(0.0)
    , class_id(0)
    , octave(0)
    , response(0.0)
    , size(0.0)  {
    }
  KeyPoint_(const ContainerAllocator& _alloc)
    : x_pos(0.0)
    , y_pos(0.0)
    , angle(0.0)
    , class_id(0)
    , octave(0)
    , response(0.0)
    , size(0.0)  {
  (void)_alloc;
    }



   typedef float _x_pos_type;
  _x_pos_type x_pos;

   typedef float _y_pos_type;
  _y_pos_type y_pos;

   typedef float _angle_type;
  _angle_type angle;

   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef int32_t _octave_type;
  _octave_type octave;

   typedef float _response_type;
  _response_type response;

   typedef float _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::opt_msgs::KeyPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opt_msgs::KeyPoint_<ContainerAllocator> const> ConstPtr;

}; // struct KeyPoint_

typedef ::opt_msgs::KeyPoint_<std::allocator<void> > KeyPoint;

typedef boost::shared_ptr< ::opt_msgs::KeyPoint > KeyPointPtr;
typedef boost::shared_ptr< ::opt_msgs::KeyPoint const> KeyPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opt_msgs::KeyPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opt_msgs::KeyPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'opt_msgs': ['/root/workspace/ros/src/open_ptrack/opt_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::KeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::KeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::KeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::KeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::KeyPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::KeyPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opt_msgs::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f03f2cb074dbed0d0c3a48cd81472cd8";
  }

  static const char* value(const ::opt_msgs::KeyPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf03f2cb074dbed0dULL;
  static const uint64_t static_value2 = 0x0c3a48cd81472cd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::opt_msgs::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opt_msgs/KeyPoint";
  }

  static const char* value(const ::opt_msgs::KeyPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opt_msgs::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ROS message used to transfer an OpenCV cv::KeyPoint object\n"
"#\n"
"# author: Carlo Rizzardo (c-rizz)\n"
"\n"
"\n"
"# The y pixel position of the keypoint in the image\n"
"float32 x_pos\n"
"\n"
"# The y pixel position of the keypoint in the image\n"
"float32 y_pos\n"
"\n"
"# The angle of the keypoint\n"
"float32 angle\n"
"\n"
"# object class (if the keypoints need to be clustered by an object they belong to)\n"
"int32 class_id\n"
"\n"
"# octave (pyramid layer) from which the keypoint has been extracted\n"
"int32 octave\n"
"\n"
"# the response by which the most strong keypoints have been selected. Can be used for the further sorting or subsampling\n"
"float32 response\n"
"\n"
"# diameter of the meaningful keypoint neighborhood\n"
"float32 size\n"
;
  }

  static const char* value(const ::opt_msgs::KeyPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opt_msgs::KeyPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_pos);
      stream.next(m.y_pos);
      stream.next(m.angle);
      stream.next(m.class_id);
      stream.next(m.octave);
      stream.next(m.response);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opt_msgs::KeyPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opt_msgs::KeyPoint_<ContainerAllocator>& v)
  {
    s << indent << "x_pos: ";
    Printer<float>::stream(s, indent + "  ", v.x_pos);
    s << indent << "y_pos: ";
    Printer<float>::stream(s, indent + "  ", v.y_pos);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "octave: ";
    Printer<int32_t>::stream(s, indent + "  ", v.octave);
    s << indent << "response: ";
    Printer<float>::stream(s, indent + "  ", v.response);
    s << indent << "size: ";
    Printer<float>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPT_MSGS_MESSAGE_KEYPOINT_H
